// Code generated by goctl. DO NOT EDIT.
// Source: identity.proto

package identityclient

import (
	"context"

	"train-tiktok/service/identity/types/identity"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RegisterReq  = identity.RegisterReq
	RegisterResp = identity.RegisterResp
	Resp         = identity.Resp

	Identity interface {
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	}

	defaultIdentity struct {
		cli zrpc.Client
	}
)

func NewIdentity(cli zrpc.Client) Identity {
	return &defaultIdentity{
		cli: cli,
	}
}

func (m *defaultIdentity) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := identity.NewIdentityClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}
