// Code generated by goctl. DO NOT EDIT.
// Source: identity.proto

package server

import (
	"context"

	"train-tiktok/service/identity/internal/logic"
	"train-tiktok/service/identity/internal/svc"
	"train-tiktok/service/identity/types/identity"
)

type IdentityServer struct {
	svcCtx *svc.ServiceContext
	identity.UnimplementedIdentityServer
}

func NewIdentityServer(svcCtx *svc.ServiceContext) *IdentityServer {
	return &IdentityServer{
		svcCtx: svcCtx,
	}
}

func (s *IdentityServer) Register(ctx context.Context, in *identity.RegisterReq) (*identity.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
