version: '3'

networks:
  tiktok_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:
  service-identity:
    build:
      context: .
      dockerfile: service/identity/Dockerfile
    container_name: service-identity
    # ports:
    #   - "8081:8081"
    volumes:
      - ./tiktok/logs/identity:/app/logs
    env_file:
      - .env
    networks:
      - tiktok_net
    restart: always

  service-user:
    build:
      context: .
      dockerfile: service/user/Dockerfile
    container_name: service-user
    # ports:
    #   - "8082:8082"
    volumes:
      - ./tiktok/logs/user:/app/logs
    env_file:
      - .env
    networks:
      - tiktok_net
    restart: always

  service-video:
    build:
      context: .
      dockerfile: service/video/Dockerfile
    container_name: service-video
    # ports:
    #   - "8083:8083"
    volumes:
      - ./tiktok/logs/video:/app/logs
    env_file:
      - .env
    networks:
      - tiktok_net
    restart: always

  service-chat:
    build:
      context: .
      dockerfile: service/chat/Dockerfile
    container_name: service-chat
    # ports:
    #   - "8083:8083"
    volumes:
      - ./tiktok/logs/chat:/app/logs
    env_file:
      - .env
    networks:
      - tiktok_net
    restart: always


  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - ./tiktok/public:/app/public
      - ./tiktok/logs/gateway:/app/logs
    networks:
      - tiktok_net
    restart: always