version: '3'

networks:
  tiktok_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:
  service-identity:
    image: ghcr.io/soxft/tiktok-service-identity:latest
    container_name: service-identity
    # ports:
    #   - "8081:8081"
    env_file:
      - .env
    networks:
      - tiktok_net
    restart: always

  service-user:
    image: ghcr.io/soxft/tiktok-service-user:latest
    container_name: service-user
    # ports:
    #   - "8082:8082"
    env_file:
      - .env
    volumes:
      - ./tiktok/public:/app/public
    networks:
      - tiktok_net
    restart: always

  service-video:
    image: ghcr.io/soxft/tiktok-service-video:latest
    container_name: service-video
    # ports:
    #   - "8083:8083"
    env_file:
      - .env
    networks:
      - tiktok_net
    restart: always

  service-chat:
    image: ghcr.io/soxft/tiktok-service-chat:latest
    container_name: service-chat
    # ports:
    #   - "8083:8083"
    env_file:
      - .env
    networks:
      - tiktok_net
    restart: always


  gateway:
    image: ghcr.io/soxft/tiktok-gateway:latest
    container_name: gateway
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - ./tiktok/public:/app/public
    networks:
      - tiktok_net
    restart: always