version: '3'

# 项目依赖的环境
services:
  # 服务发现
  etcd:
    image: bitnami/etcd:3.5.0
    container_name: etcd-server
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
    ports: # 设置端口映射
      - "2379:2379"
    networks:
      - tiktok
    restart: always

  mysql:
    image: mysql/mysql-server:8.0.28
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
    env_file:
      - .env
    ports:
      - "127.0.0.1:33066:3306"
    volumes:
      - ./tiktok/mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    restart: always
    networks:
      - tiktok

  #redis容器
  redis:
    image: redis:7.0.0-alpine
    container_name: redis
    ports:
      - "127.0.0.1:63379:6379"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      - ./tiktok/redis/data:/data:rw
    command: "redis-server --appendonly yes"
    privileged: true
    restart: always
    networks:
      - tiktok

networks:
  tiktok_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16