// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"train-tiktok/service/video/internal/logic"
	"train-tiktok/service/video/internal/svc"
	"train-tiktok/service/video/types/video"
)

type VideosServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideosServer
}

func NewVideosServer(svcCtx *svc.ServiceContext) *VideosServer {
	return &VideosServer{
		svcCtx: svcCtx,
	}
}

func (s *VideosServer) Publish(ctx context.Context, in *video.PublishReq) (*video.PublishResp, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *VideosServer) Feed(ctx context.Context, in *video.FeedReq) (*video.FeedResp, error) {
	l := logic.NewFeedLogic(ctx, s.svcCtx)
	return l.Feed(in)
}

func (s *VideosServer) CommentAction(ctx context.Context, in *video.CommentActionReq) (*video.CommentActionResp, error) {
	l := logic.NewCommentActionLogic(ctx, s.svcCtx)
	return l.CommentAction(in)
}

func (s *VideosServer) CommentList(ctx context.Context, in *video.CommentListReq) (*video.CommentListResp, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}

func (s *VideosServer) FavoriteAction(ctx context.Context, in *video.FavoriteActionReq) (*video.FavoriteActionResp, error) {
	l := logic.NewFavoriteActionLogic(ctx, s.svcCtx)
	return l.FavoriteAction(in)
}

func (s *VideosServer) FavoriteList(ctx context.Context, in *video.FavoriteListReq) (*video.FavoriteListResp, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}

func (s *VideosServer) FavoriteCount(ctx context.Context, in *video.FavoriteCountReq) (*video.FavoriteCountResp, error) {
	l := logic.NewFavoriteCountLogic(ctx, s.svcCtx)
	return l.FavoriteCount(in)
}

func (s *VideosServer) CommentCount(ctx context.Context, in *video.CommentCountReq) (*video.CommentCountResp, error) {
	l := logic.NewCommentCountLogic(ctx, s.svcCtx)
	return l.CommentCount(in)
}

func (s *VideosServer) IsFavorite(ctx context.Context, in *video.IsFavoriteReq) (*video.IsFavoriteResp, error) {
	l := logic.NewIsFavoriteLogic(ctx, s.svcCtx)
	return l.IsFavorite(in)
}
