// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"train-tiktok/service/video/internal/logic"
	"train-tiktok/service/video/internal/svc"
	"train-tiktok/service/video/types/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServer) Publish(ctx context.Context, in *video.PublishReq) (*video.PublishResp, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *VideoServer) Feed(ctx context.Context, in *video.FeedReq) (*video.FeedResp, error) {
	l := logic.NewFeedLogic(ctx, s.svcCtx)
	return l.Feed(in)
}
