// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatClient interface {
	ChatAction(ctx context.Context, in *ChatActionReq, opts ...grpc.CallOption) (*CharActionResp, error)
	ChatMessage(ctx context.Context, in *ChatMessageReq, opts ...grpc.CallOption) (*ChatMessageResp, error)
	ChatLastMessage(ctx context.Context, in *ChatLastMessageReq, opts ...grpc.CallOption) (*ChatLastMessageResp, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) ChatAction(ctx context.Context, in *ChatActionReq, opts ...grpc.CallOption) (*CharActionResp, error) {
	out := new(CharActionResp)
	err := c.cc.Invoke(ctx, "/chat.chat/chatAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatMessage(ctx context.Context, in *ChatMessageReq, opts ...grpc.CallOption) (*ChatMessageResp, error) {
	out := new(ChatMessageResp)
	err := c.cc.Invoke(ctx, "/chat.chat/chatMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatLastMessage(ctx context.Context, in *ChatLastMessageReq, opts ...grpc.CallOption) (*ChatLastMessageResp, error) {
	out := new(ChatLastMessageResp)
	err := c.cc.Invoke(ctx, "/chat.chat/chatLastMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility
type ChatServer interface {
	ChatAction(context.Context, *ChatActionReq) (*CharActionResp, error)
	ChatMessage(context.Context, *ChatMessageReq) (*ChatMessageResp, error)
	ChatLastMessage(context.Context, *ChatLastMessageReq) (*ChatLastMessageResp, error)
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (UnimplementedChatServer) ChatAction(context.Context, *ChatActionReq) (*CharActionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatAction not implemented")
}
func (UnimplementedChatServer) ChatMessage(context.Context, *ChatMessageReq) (*ChatMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatMessage not implemented")
}
func (UnimplementedChatServer) ChatLastMessage(context.Context, *ChatLastMessageReq) (*ChatLastMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatLastMessage not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_ChatAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.chat/chatAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatAction(ctx, req.(*ChatActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.chat/chatMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatMessage(ctx, req.(*ChatMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatLastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatLastMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatLastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.chat/chatLastMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatLastMessage(ctx, req.(*ChatLastMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "chatAction",
			Handler:    _Chat_ChatAction_Handler,
		},
		{
			MethodName: "chatMessage",
			Handler:    _Chat_ChatMessage_Handler,
		},
		{
			MethodName: "chatLastMessage",
			Handler:    _Chat_ChatLastMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
