// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package identity

import (
	"context"

	"train-tiktok/service/user/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Resp     = user.Resp
	UserReq  = user.UserReq
	UserResp = user.UserResp

	Identity interface {
		User(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserResp, error)
	}

	defaultIdentity struct {
		cli zrpc.Client
	}
)

func NewIdentity(cli zrpc.Client) Identity {
	return &defaultIdentity{
		cli: cli,
	}
}

func (m *defaultIdentity) User(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserResp, error) {
	client := user.NewIdentityClient(m.cli.Conn())
	return client.User(ctx, in, opts...)
}
