// Code generated by goctl. DO NOT EDIT.
package types

type PingResp struct {
	Resp
	Msg string `json:"msg"`
}

type Resp struct {
	Code int32  `json:"status_code"`
	Msg  string `json:"status_msg"`
}

type LoginReq struct {
	Username string `json:"username"` // max 32 chars
	Password string `json:"password"` // max 32 chars
}

type LoginResp struct {
	Resp
	Token  string `json:"token"`
	UserId int64  `json:"user_id"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Resp
	Token  string `json:"token"`
	UserId int64  `json:"user_id"`
}
