CREATE DATABASE IF NOT EXISTS `tiktok` DEFAULT CHARACTER SET utf8 COLLATE utf8mb4;
CREATE USER 'tiktok'@'%' IDENTIFIED BY 'tiktok';
GRANT ALL PRIVILEGES ON `tiktok`.* TO 'tiktok'@'%';
FLUSH PRIVILEGES;
