// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"train-tiktok/service/user/internal/logic"
	"train-tiktok/service/user/internal/svc"
	"train-tiktok/service/user/types/user"
)

type IdentityServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedIdentityServer
}

func NewIdentityServer(svcCtx *svc.ServiceContext) *IdentityServer {
	return &IdentityServer{
		svcCtx: svcCtx,
	}
}

func (s *IdentityServer) User(ctx context.Context, in *user.UserReq) (*user.UserResp, error) {
	l := logic.NewUserLogic(ctx, s.svcCtx)
	return l.User(in)
}
