// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package server

import (
	"context"

	"train-tiktok/service/chat/internal/logic"
	"train-tiktok/service/chat/internal/svc"
	"train-tiktok/service/chat/types/chat"
)

type ChatServer struct {
	svcCtx *svc.ServiceContext
	chat.UnimplementedChatServer
}

func NewChatServer(svcCtx *svc.ServiceContext) *ChatServer {
	return &ChatServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServer) ChatAction(ctx context.Context, in *chat.ChatActionReq) (*chat.CharActionResp, error) {
	l := logic.NewChatActionLogic(ctx, s.svcCtx)
	return l.ChatAction(in)
}

func (s *ChatServer) ChatMessage(ctx context.Context, in *chat.ChatMessageReq) (*chat.ChatMessageResp, error) {
	l := logic.NewChatMessageLogic(ctx, s.svcCtx)
	return l.ChatMessage(in)
}
