name: Docker Build Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gateway-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build-and-publish
        uses: macbre/push-to-ghcr@master
        with:
          image_name: soxft/tiktok-gateway
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./gateway/Dockerfile

  service-identity-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build-and-publish
        uses: macbre/push-to-ghcr@master
        with:
          image_name: soxft/tiktok-service-identity
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./service/identity/Dockerfile



  service-user-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build-and-publish
        uses: macbre/push-to-ghcr@master
        with:
          image_name: soxft/tiktok-service-user
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./service/user/Dockerfile


  service-video-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build-and-publish
        uses: macbre/push-to-ghcr@master
        with:
          image_name: soxft/tiktok-service-video
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./service/video/Dockerfile

  service-chat-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build-and-publish
        uses: macbre/push-to-ghcr@master
        with:
          image_name: soxft/tiktok-service-chat
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./service/chat/Dockerfile