name: Docker Build Push

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  gateway-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build-and-publish
        uses: macbre/push-to-ghcr@master
        with:
          image_name: l-evi/tiktok-gateway
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./gateway/Dockerfile